// <auto-generated />
namespace mis4200_team15.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class LocationscoreValuesUserValues : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LocationscoreValuesUserValues));
        
        string IMigrationMetadata.Id
        {
            get { return "202003272219064_Locations, coreValues, UserValues"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
