// <auto-generated />
namespace mis4200_team15.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class recog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(recog));
        
        string IMigrationMetadata.Id
        {
            get { return "202004240138054_recog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
